{
  "openapi": "3.1.0",
  "info": {
    "title": "Simple CRUD",
    "summary": "This is OpenAPI schema for simple CRUD service",
    "version": "develop-7a36ce1e"
  },
  "servers": [
    {
      "url": "/driver"
    }
  ],
  "paths": {
    "/api/v1/drivers/": {
      "get": {
        "tags": [
          "Drivers"
        ],
        "summary": "List Drivers",
        "operationId": "list_drivers_api_v1_drivers__get",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Id"
            }
          },
          {
            "name": "creator_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Creator Id"
            }
          },
          {
            "name": "search_like_string",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Search Like String"
            }
          },
          {
            "name": "is_active",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Is Active"
            }
          },
          {
            "name": "fmp_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Fmp Id"
            }
          },
          {
            "name": "first_name",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "First Name"
            }
          },
          {
            "name": "last_name",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Last Name"
            }
          },
          {
            "name": "middle_name",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Middle Name"
            }
          },
          {
            "name": "is_fired",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Is Fired"
            }
          },
          {
            "name": "contractor_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "integer",
                  "maximum": 2147483647,
                  "minimum": -2147483647
                },
                {
                  "type": "null"
                }
              ],
              "title": "Contractor Id"
            }
          },
          {
            "name": "phone_number",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Phone Number"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 50,
              "title": "Limit"
            }
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 0,
              "title": "Offset"
            }
          },
          {
            "name": "sort_by",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string",
                  "pattern": "([a-zA-Z_]+).(asc|desc)"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Sort By"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseList_DriverSchema_"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "post": {
        "tags": [
          "Drivers"
        ],
        "summary": "Create Driver",
        "operationId": "create_driver_api_v1_drivers__post",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateDriverSchema"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/drivers/{driver_id}/": {
      "get": {
        "tags": [
          "Drivers"
        ],
        "summary": "Get Driver By Id",
        "operationId": "get_driver_by_id_api_v1_drivers__driver_id___get",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "driver_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Driver Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "patch": {
        "tags": [
          "Drivers"
        ],
        "summary": "Update Driver",
        "operationId": "update_driver_api_v1_drivers__driver_id___patch",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "driver_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Driver Id"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateDriverSchema"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "delete": {
        "tags": [
          "Drivers"
        ],
        "summary": "Deactivate Driver",
        "operationId": "deactivate_driver_api_v1_drivers__driver_id___delete",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "driver_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Driver Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/drivers/{driver_id}/activate/": {
      "patch": {
        "tags": [
          "Drivers"
        ],
        "summary": "Activate Driver",
        "operationId": "activate_driver_api_v1_drivers__driver_id__activate__patch",
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "driver_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Driver Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DriverSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateDriverSchema": {
        "properties": {
          "contractor_id": {
            "anyOf": [
              {
                "type": "integer",
                "maximum": 2147483647.0,
                "minimum": -2147483647.0
              },
              {
                "type": "null"
              }
            ],
            "title": "Contractor Id"
          },
          "phone_number": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^\\d{7,15}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Phone Number"
          },
          "fmp_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Fmp Id"
          },
          "first_name": {
            "type": "string",
            "minLength": 1,
            "title": "First Name"
          },
          "middle_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Middle Name"
          },
          "last_name": {
            "type": "string",
            "minLength": 1,
            "title": "Last Name"
          },
          "is_fired": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Is Fired"
          }
        },
        "type": "object",
        "required": [
          "first_name",
          "last_name"
        ],
        "title": "CreateDriverSchema"
      },
      "DriverSchema": {
        "properties": {
          "contractor_id": {
            "anyOf": [
              {
                "type": "integer",
                "maximum": 2147483647.0,
                "minimum": -2147483647.0
              },
              {
                "type": "null"
              }
            ],
            "title": "Contractor Id"
          },
          "id": {
            "type": "integer",
            "title": "Id"
          },
          "created_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Created At"
          },
          "updated_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Updated At"
          },
          "creator_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Id"
          },
          "name": {
            "type": "string",
            "title": "Name"
          },
          "is_active": {
            "type": "boolean",
            "title": "Is Active"
          },
          "fmp_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Fmp Id"
          },
          "first_name": {
            "type": "string",
            "title": "First Name"
          },
          "middle_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Middle Name"
          },
          "last_name": {
            "type": "string",
            "title": "Last Name"
          },
          "is_fired": {
            "type": "boolean",
            "title": "Is Fired"
          },
          "phone_number": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Phone Number"
          }
        },
        "type": "object",
        "required": [
          "id",
          "name",
          "is_active",
          "first_name",
          "last_name",
          "is_fired"
        ],
        "title": "DriverSchema"
      },
      "ResponseList_DriverSchema_": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/DriverSchema"
            },
            "type": "array",
            "title": "Items"
          },
          "count": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Count"
          },
          "limit": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Limit"
          },
          "offset": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Offset"
          }
        },
        "type": "object",
        "required": [
          "items"
        ],
        "title": "ResponseList[DriverSchema]"
      },
      "UpdateDriverSchema": {
        "properties": {
          "contractor_id": {
            "anyOf": [
              {
                "type": "integer",
                "maximum": 2147483647.0,
                "minimum": -2147483647.0
              },
              {
                "type": "null"
              }
            ],
            "title": "Contractor Id"
          },
          "phone_number": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^\\d{7,15}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Phone Number"
          },
          "first_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "First Name"
          },
          "middle_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Middle Name"
          },
          "last_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Last Name"
          },
          "is_fired": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Is Fired"
          }
        },
        "type": "object",
        "title": "UpdateDriverSchema"
      }
    },
    "securitySchemes": {
      "HTTPBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
