{
  "openapi": "3.1.0",
  "info": {
    "title": "Medium",
    "summary": "This is OpenAPI schema for medium service",
    "version": "development"
  },
  "servers": [
    {
      "url": "/flow-ims"
    }
  ],
  "paths": {
    "/api/v1/camera-models/{model_id}/": {
      "get": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Get One",
        "operationId": "get_one_api_v1_camera_models__model_id___get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Model Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraModelSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "patch": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Update One",
        "operationId": "update_one_api_v1_camera_models__model_id___patch",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Model Id"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CameraModelSchemaPatch"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraModelSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "delete": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Deactivate One",
        "operationId": "deactivate_one_api_v1_camera_models__model_id___delete",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Model Id"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/camera-models/": {
      "get": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Get List",
        "operationId": "get_list_api_v1_camera_models__get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 50,
              "title": "Limit"
            }
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 0,
              "title": "Offset"
            }
          },
          {
            "name": "sort_by",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string",
                  "pattern": "([a-zA-Z_]+).(asc|desc)"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Sort By"
            }
          },
          {
            "name": "is_active",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "default": true,
              "title": "Is Active"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseList_CameraModelSchema_"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "post": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Create One",
        "operationId": "create_one_api_v1_camera_models__post",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CameraModelSchemaCreate"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraModelSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/camera-models/{model_id}/activate/": {
      "patch": {
        "tags": [
          "Camera Models"
        ],
        "summary": "Activate One",
        "operationId": "activate_one_api_v1_camera_models__model_id__activate__patch",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Model Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraModelSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/cameras/next-code/": {
      "post": {
        "tags": [
          "Cameras"
        ],
        "summary": "Next Camera Code",
        "operationId": "next_camera_code_api_v1_cameras_next_code__post",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraNextCodeSchema"
                }
              }
            }
          },
          "401": {
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "403": {
            "description": "The server understood the request but refuses to authorize it.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ]
      }
    },
    "/api/v1/cameras/{camera_id}/": {
      "get": {
        "tags": [
          "Cameras"
        ],
        "summary": "Get One",
        "operationId": "get_one_api_v1_cameras__camera_id___get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "camera_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Camera Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "patch": {
        "tags": [
          "Cameras"
        ],
        "summary": "Update One",
        "operationId": "update_one_api_v1_cameras__camera_id___patch",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "camera_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Camera Id"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CameraSchemaPatch"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "delete": {
        "tags": [
          "Cameras"
        ],
        "summary": "Deactivate One",
        "operationId": "deactivate_one_api_v1_cameras__camera_id___delete",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "camera_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Camera Id"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/cameras/": {
      "post": {
        "tags": [
          "Cameras"
        ],
        "summary": "Create One",
        "operationId": "create_one_api_v1_cameras__post",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CameraSchemaCreate"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      },
      "get": {
        "tags": [
          "Cameras"
        ],
        "summary": "Get List",
        "operationId": "get_list_api_v1_cameras__get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 50,
              "title": "Limit"
            }
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": 0,
              "default": 0,
              "title": "Offset"
            }
          },
          {
            "name": "sort_by",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string",
                  "pattern": "([a-zA-Z_]+).(asc|desc)"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Sort By"
            }
          },
          {
            "name": "is_active",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "default": true,
              "title": "Is Active"
            }
          },
          {
            "name": "calibration_status",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "$ref": "#/components/schemas/CalibrationStatus"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Calibration Status"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseList_CameraSchema_"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/cameras/bulk/": {
      "post": {
        "tags": [
          "Cameras"
        ],
        "summary": "Create Bulk",
        "operationId": "create_bulk_api_v1_cameras_bulk__post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CameraSchemaBulkCreate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseBulkCreateCameraSchema"
                }
              }
            }
          },
          "401": {
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "403": {
            "description": "The server understood the request but refuses to authorize it.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ]
      }
    },
    "/api/v1/cameras/{camera_id}/activate/": {
      "patch": {
        "tags": [
          "Cameras"
        ],
        "summary": "Activate One",
        "operationId": "activate_one_api_v1_cameras__camera_id__activate__patch",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "camera_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Camera Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/cameras/filter-counter/": {
      "get": {
        "tags": [
          "Cameras"
        ],
        "summary": "Count By Status",
        "operationId": "count_by_status_api_v1_cameras_filter_counter__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CameraCountByStatus"
                }
              }
            }
          },
          "401": {
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "403": {
            "description": "The server understood the request but refuses to authorize it.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "CalibrationStatus": {
        "type": "string",
        "enum": [
          "calibrated",
          "uncalibrated"
        ],
        "title": "CalibrationStatus"
      },
      "CameraCountByStatus": {
        "properties": {
          "calibrated": {
            "type": "integer",
            "maximum": 2147483647.0,
            "minimum": -2147483647.0,
            "title": "Calibrated"
          },
          "uncalibrated": {
            "type": "integer",
            "maximum": 2147483647.0,
            "minimum": -2147483647.0,
            "title": "Uncalibrated"
          }
        },
        "type": "object",
        "required": [
          "calibrated",
          "uncalibrated"
        ],
        "title": "CameraCountByStatus"
      },
      "CameraModelLensId": {
        "type": "string",
        "enum": [
          "a",
          "b",
          "c",
          "d",
          "Undefined"
        ],
        "title": "CameraModelLensId"
      },
      "CameraModelSchema": {
        "properties": {
          "id": {
            "type": "integer",
            "title": "Id"
          },
          "created_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Created At"
          },
          "updated_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Updated At"
          },
          "creator_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Id"
          },
          "is_active": {
            "type": "boolean",
            "title": "Is Active"
          },
          "name": {
            "type": "string",
            "title": "Name"
          },
          "lens_id": {
            "$ref": "#/components/schemas/CameraModelLensId"
          }
        },
        "type": "object",
        "required": [
          "id",
          "is_active",
          "name",
          "lens_id"
        ],
        "title": "CameraModelSchema"
      },
      "CameraModelSchemaCreate": {
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "lens_id": {
            "$ref": "#/components/schemas/CameraModelLensId"
          }
        },
        "type": "object",
        "required": [
          "name",
          "lens_id"
        ],
        "title": "CameraModelSchemaCreate"
      },
      "CameraModelSchemaPatch": {
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "lens_id": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/CameraModelLensId"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "type": "object",
        "title": "CameraModelSchemaPatch"
      },
      "CameraNextCodeSchema": {
        "properties": {
          "code": {
            "type": "string",
            "title": "Code"
          }
        },
        "type": "object",
        "required": [
          "code"
        ],
        "title": "CameraNextCodeSchema"
      },
      "CameraSchema": {
        "properties": {
          "id": {
            "type": "integer",
            "title": "Id"
          },
          "created_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Created At"
          },
          "updated_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Updated At"
          },
          "creator_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Id"
          },
          "is_active": {
            "type": "boolean",
            "title": "Is Active"
          },
          "code": {
            "type": "string",
            "title": "Code"
          },
          "calibration_status": {
            "$ref": "#/components/schemas/CalibrationStatus"
          },
          "calibration_date": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Calibration Date"
          },
          "model": {
            "$ref": "#/components/schemas/CameraModelSchema"
          }
        },
        "type": "object",
        "required": [
          "id",
          "is_active",
          "code",
          "calibration_status",
          "model"
        ],
        "title": "CameraSchema"
      },
      "CameraSchemaBulkCreate": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/CameraSchemaCreate"
            },
            "type": "array",
            "title": "Items"
          }
        },
        "type": "object",
        "required": [
          "items"
        ],
        "title": "CameraSchemaBulkCreate"
      },
      "CameraSchemaCreate": {
        "properties": {
          "code": {
            "type": "string",
            "title": "Code"
          },
          "model_id": {
            "type": "integer",
            "maximum": 2147483647.0,
            "minimum": -2147483647.0,
            "title": "Model Id"
          },
          "attributes": {
            "type": "object",
            "title": "Attributes"
          }
        },
        "type": "object",
        "required": [
          "code",
          "model_id"
        ],
        "title": "CameraSchemaCreate"
      },
      "CameraSchemaPatch": {
        "properties": {
          "model_id": {
            "anyOf": [
              {
                "type": "integer",
                "maximum": 2147483647.0,
                "minimum": -2147483647.0
              },
              {
                "type": "null"
              }
            ],
            "title": "Model Id"
          },
          "code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Code"
          },
          "attributes": {
            "anyOf": [
              {
                "type": "object"
              },
              {
                "type": "null"
              }
            ],
            "title": "Attributes"
          }
        },
        "type": "object",
        "title": "CameraSchemaPatch"
      },
      "ResponseBulkCreateCameraSchema": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/CameraSchema"
            },
            "type": "array",
            "title": "Items"
          },
          "created": {
            "type": "integer",
            "maximum": 2147483647.0,
            "minimum": -2147483647.0,
            "title": "Created"
          }
        },
        "type": "object",
        "required": [
          "items",
          "created"
        ],
        "title": "ResponseBulkCreateCameraSchema"
      },
      "ResponseList_CameraModelSchema_": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/CameraModelSchema"
            },
            "type": "array",
            "title": "Items"
          },
          "count": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Count"
          },
          "limit": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Limit"
          },
          "offset": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Offset"
          }
        },
        "type": "object",
        "required": [
          "items"
        ],
        "title": "ResponseList[CameraModelSchema]"
      },
      "ResponseList_CameraSchema_": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/CameraSchema"
            },
            "type": "array",
            "title": "Items"
          },
          "count": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Count"
          },
          "limit": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Limit"
          },
          "offset": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Offset"
          }
        },
        "type": "object",
        "required": [
          "items"
        ],
        "title": "ResponseList[CameraSchema]"
      }
    },
    "securitySchemes": {
      "HTTPBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
