{
  "openapi": "3.1.0",
  "info": {
    "title": "Enums",
    "summary": "This is OpenAPI schema for enums service",
    "version": "development"
  },
  "servers": [
    {
      "url": "/ui-notification"
    }
  ],
  "paths": {
    "/api/v1/notifications/": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "Get List",
        "operationId": "get_list_api_v1_notifications__get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 50,
              "title": "Limit"
            }
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 0,
              "title": "Offset"
            }
          },
          {
            "name": "sort_by",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string",
                  "pattern": "([a-zA-Z_]+).(asc|desc)"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Sort By"
            }
          },
          {
            "name": "search_like_string",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Search Like String"
            }
          },
          {
            "name": "is_active",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "default": true,
              "title": "Is Active"
            }
          },
          {
            "name": "recipient_username",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Recipient Username"
            }
          },
          {
            "name": "is_read",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Is Read"
            }
          },
          {
            "name": "is_unread",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Is Unread"
            }
          },
          {
            "name": "job_type_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "integer",
                  "maximum": 2147483647,
                  "minimum": -2147483647
                },
                {
                  "type": "null"
                }
              ],
              "title": "Job Type Id"
            }
          },
          {
            "name": "priority_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Priority Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseList_NotificationSchema_"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/notifications/{item_id}/": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "Get One",
        "operationId": "get_one_api_v1_notifications__item_id___get",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "item_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Item Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotificationBriefSchema"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/notifications/mark-all-as-read/": {
      "post": {
        "tags": [
          "Notifications"
        ],
        "summary": "Mark All As Read",
        "operationId": "mark_all_as_read_api_v1_notifications_mark_all_as_read__post",
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "401": {
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "403": {
            "description": "The server understood the request but refuses to authorize it.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ]
      }
    },
    "/api/v1/notifications/{notification_id}/mark-as-read/": {
      "post": {
        "tags": [
          "Notifications"
        ],
        "summary": "Mark As Read",
        "operationId": "mark_as_read_api_v1_notifications__notification_id__mark_as_read__post",
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ],
        "parameters": [
          {
            "name": "notification_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "maximum": 2147483647,
              "minimum": -2147483647,
              "title": "Notification Id"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource."
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understood the request but refuses to authorize it."
          },
          "422": {
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            },
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions."
          }
        }
      }
    },
    "/api/v1/notifications/unread/count/": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "Get Unread Count",
        "operationId": "get_unread_count_api_v1_notifications_unread_count__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotificationsCountSchema"
                }
              }
            }
          },
          "401": {
            "description": "The request has not been applied because it lacks valid authentication credentials for the target resource.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNAUTHORIZED",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "403": {
            "description": "The server understood the request but refuses to authorize it.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "FORBIDDEN",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "The server understands the content type of the request entity but was unable to process the contained instructions.",
            "content": {
              "application/json": {
                "example": {
                  "error": {
                    "code": "UNPROCESSABLE_ENTITY",
                    "message": "Error message",
                    "details": {}
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "HTTPBearer": []
          },
          {
            "HTTPBearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "NotificationBriefSchema": {
        "properties": {
          "id": {
            "type": "integer",
            "title": "Id"
          },
          "created_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Created At"
          },
          "updated_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Updated At"
          },
          "creator_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Id"
          },
          "is_active": {
            "type": "boolean",
            "title": "Is Active"
          },
          "event": {
            "$ref": "#/components/schemas/NotificationEventEnum"
          },
          "read_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Read At"
          },
          "payload": {
            "$ref": "#/components/schemas/TaskNotificationPayloadBase"
          },
          "task_snapshot": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/TaskSnapshot"
              },
              {
                "$ref": "#/components/schemas/TaskWithReservationSnapshot"
              }
            ],
            "title": "Task Snapshot"
          }
        },
        "type": "object",
        "required": [
          "id",
          "is_active",
          "event",
          "read_at",
          "payload",
          "task_snapshot"
        ],
        "title": "NotificationBriefSchema"
      },
      "NotificationEventEnum": {
        "type": "string",
        "enum": [
          "task_create",
          "task_new_assignee",
          "task_old_assignee",
          "task_update",
          "task_delete",
          "task_and_reservation_create",
          "task_and_reservation_update",
          "task_and_reservation_new_assignee",
          "task_and_reservation_old_assignee",
          "task_and_reservation_delete",
          "vehicle_checkup_not_passed"
        ],
        "title": "NotificationEventEnum"
      },
      "NotificationSchema": {
        "properties": {
          "id": {
            "type": "integer",
            "title": "Id"
          },
          "created_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Created At"
          },
          "updated_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Updated At"
          },
          "creator_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Id"
          },
          "is_active": {
            "type": "boolean",
            "title": "Is Active"
          },
          "event": {
            "$ref": "#/components/schemas/NotificationEventEnum"
          },
          "read_at": {
            "anyOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ],
            "title": "Read At"
          },
          "payload": {
            "$ref": "#/components/schemas/TaskNotificationPayloadBase"
          }
        },
        "type": "object",
        "required": [
          "id",
          "is_active",
          "event",
          "read_at",
          "payload"
        ],
        "title": "NotificationSchema"
      },
      "NotificationsCountSchema": {
        "properties": {
          "count": {
            "type": "integer",
            "title": "Count"
          }
        },
        "type": "object",
        "required": [
          "count"
        ],
        "title": "NotificationsCountSchema"
      },
      "ResponseList_NotificationSchema_": {
        "properties": {
          "items": {
            "items": {
              "$ref": "#/components/schemas/NotificationSchema"
            },
            "type": "array",
            "title": "Items"
          },
          "count": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Count"
          },
          "limit": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Limit"
          },
          "offset": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Offset"
          }
        },
        "type": "object",
        "required": [
          "items"
        ],
        "title": "ResponseList[NotificationSchema]"
      },
      "TaskNotificationPayloadBase": {
        "properties": {
          "initiator_full_name": {
            "type": "string",
            "title": "Initiator Full Name"
          },
          "task_id": {
            "type": "integer",
            "title": "Task Id"
          },
          "priority_id": {
            "type": "integer",
            "title": "Priority Id"
          },
          "priority_name": {
            "type": "string",
            "title": "Priority Name"
          },
          "priority_title": {
            "type": "string",
            "title": "Priority Title"
          }
        },
        "type": "object",
        "required": [
          "initiator_full_name",
          "task_id",
          "priority_id",
          "priority_name",
          "priority_title"
        ],
        "title": "TaskNotificationPayloadBase"
      },
      "TaskSnapshot": {
        "properties": {
          "assignee_first_name": {
            "type": "string",
            "title": "Assignee First Name"
          },
          "assignee_last_name": {
            "type": "string",
            "title": "Assignee Last Name"
          },
          "assignee_second_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Assignee Second Name"
          },
          "creator_first_name": {
            "type": "string",
            "title": "Creator First Name"
          },
          "creator_last_name": {
            "type": "string",
            "title": "Creator Last Name"
          },
          "creator_second_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Second Name"
          },
          "job_type_id": {
            "type": "integer",
            "title": "Job Type Id"
          },
          "job_type_title": {
            "type": "string",
            "title": "Job Type Title"
          },
          "status_title": {
            "type": "string",
            "title": "Status Title"
          }
        },
        "type": "object",
        "required": [
          "assignee_first_name",
          "assignee_last_name",
          "creator_first_name",
          "creator_last_name",
          "job_type_id",
          "job_type_title",
          "status_title"
        ],
        "title": "TaskSnapshot"
      },
      "TaskWithReservationSnapshot": {
        "properties": {
          "assignee_first_name": {
            "type": "string",
            "title": "Assignee First Name"
          },
          "assignee_last_name": {
            "type": "string",
            "title": "Assignee Last Name"
          },
          "assignee_second_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Assignee Second Name"
          },
          "creator_first_name": {
            "type": "string",
            "title": "Creator First Name"
          },
          "creator_last_name": {
            "type": "string",
            "title": "Creator Last Name"
          },
          "creator_second_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Creator Second Name"
          },
          "job_type_id": {
            "type": "integer",
            "title": "Job Type Id"
          },
          "job_type_title": {
            "type": "string",
            "title": "Job Type Title"
          },
          "status_title": {
            "type": "string",
            "title": "Status Title"
          },
          "vehicle_name": {
            "type": "string",
            "title": "Vehicle Name"
          },
          "vehicle_license": {
            "type": "string",
            "title": "Vehicle License"
          },
          "start_datetime": {
            "type": "string",
            "format": "date-time",
            "title": "Start Datetime"
          },
          "finish_datetime": {
            "type": "string",
            "format": "date-time",
            "title": "Finish Datetime"
          }
        },
        "type": "object",
        "required": [
          "assignee_first_name",
          "assignee_last_name",
          "creator_first_name",
          "creator_last_name",
          "job_type_id",
          "job_type_title",
          "status_title",
          "vehicle_name",
          "vehicle_license",
          "start_datetime",
          "finish_datetime"
        ],
        "title": "TaskWithReservationSnapshot"
      }
    },
    "securitySchemes": {
      "HTTPBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
